package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpHabitRecord;
import pri.growup.persistence.dto.GrowUpHabitRecordExample;

public interface GrowUpHabitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int countByExample(GrowUpHabitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpHabitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String habitRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int insert(GrowUpHabitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpHabitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    List<GrowUpHabitRecord> selectByExample(GrowUpHabitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    GrowUpHabitRecord selectByPrimaryKey(String habitRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpHabitRecord record, @Param("example") GrowUpHabitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpHabitRecord record, @Param("example") GrowUpHabitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpHabitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_habit_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpHabitRecord record);
}