package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpUserHibit;
import pri.growup.persistence.dto.GrowUpUserHibitExample;

public interface GrowUpUserHibitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int countByExample(GrowUpUserHibitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpUserHibitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userHabitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int insert(GrowUpUserHibit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpUserHibit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    List<GrowUpUserHibit> selectByExample(GrowUpUserHibitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    GrowUpUserHibit selectByPrimaryKey(String userHabitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpUserHibit record, @Param("example") GrowUpUserHibitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpUserHibit record, @Param("example") GrowUpUserHibitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpUserHibit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_hibit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpUserHibit record);
}