package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpSigninUser;
import pri.growup.persistence.dto.GrowUpSigninUserExample;

public interface GrowUpSigninUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int countByExample(GrowUpSigninUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpSigninUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int insert(GrowUpSigninUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpSigninUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    List<GrowUpSigninUser> selectByExample(GrowUpSigninUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    GrowUpSigninUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpSigninUser record, @Param("example") GrowUpSigninUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpSigninUser record, @Param("example") GrowUpSigninUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpSigninUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_signin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpSigninUser record);
}