package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpCommonId;
import pri.growup.persistence.dto.GrowUpCommonIdExample;

public interface GrowUpCommonIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int countByExample(GrowUpCommonIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpCommonIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int insert(GrowUpCommonId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpCommonId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    List<GrowUpCommonId> selectByExample(GrowUpCommonIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpCommonId record, @Param("example") GrowUpCommonIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_common_id
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpCommonId record, @Param("example") GrowUpCommonIdExample example);
}