package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpVlog;
import pri.growup.persistence.dto.GrowUpVlogExample;

public interface GrowUpVlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int countByExample(GrowUpVlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpVlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vlogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int insert(GrowUpVlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpVlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    List<GrowUpVlog> selectByExample(GrowUpVlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    GrowUpVlog selectByPrimaryKey(String vlogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpVlog record, @Param("example") GrowUpVlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpVlog record, @Param("example") GrowUpVlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpVlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_vlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpVlog record);
}