package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpUserSigninRecord;
import pri.growup.persistence.dto.GrowUpUserSigninRecordExample;

public interface GrowUpUserSigninRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int countByExample(GrowUpUserSigninRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpUserSigninRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String signInRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int insert(GrowUpUserSigninRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpUserSigninRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    List<GrowUpUserSigninRecord> selectByExample(GrowUpUserSigninRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    GrowUpUserSigninRecord selectByPrimaryKey(String signInRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpUserSigninRecord record, @Param("example") GrowUpUserSigninRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpUserSigninRecord record, @Param("example") GrowUpUserSigninRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpUserSigninRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_signin_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpUserSigninRecord record);
}