package pri.growup.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.growup.persistence.dto.GrowUpUserIdentity;
import pri.growup.persistence.dto.GrowUpUserIdentityExample;

public interface GrowUpUserIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int countByExample(GrowUpUserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int deleteByExample(GrowUpUserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Byte identityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int insert(GrowUpUserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int insertSelective(GrowUpUserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    List<GrowUpUserIdentity> selectByExample(GrowUpUserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    GrowUpUserIdentity selectByPrimaryKey(Byte identityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GrowUpUserIdentity record, @Param("example") GrowUpUserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GrowUpUserIdentity record, @Param("example") GrowUpUserIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowUpUserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grow_up_user_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowUpUserIdentity record);
}