package pri.growup.persistence.dto;

import java.util.Date;
import pri.growup.base.persistence.BaseDto;

public class GrowUpUserHibit extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.USER_HABIT_ID
     *
     * @mbggenerated
     */
    private String userHabitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.HABIT_ID
     *
     * @mbggenerated
     */
    private String habitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.DELETE_TIME
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_hibit.DELETE_FLG
     *
     * @mbggenerated
     */
    private Byte deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.USER_HABIT_ID
     *
     * @return the value of grow_up_user_hibit.USER_HABIT_ID
     *
     * @mbggenerated
     */
    public String getUserHabitId() {
        return userHabitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.USER_HABIT_ID
     *
     * @param userHabitId the value for grow_up_user_hibit.USER_HABIT_ID
     *
     * @mbggenerated
     */
    public void setUserHabitId(String userHabitId) {
        this.userHabitId = userHabitId == null ? null : userHabitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.USER_ID
     *
     * @return the value of grow_up_user_hibit.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.USER_ID
     *
     * @param userId the value for grow_up_user_hibit.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.HABIT_ID
     *
     * @return the value of grow_up_user_hibit.HABIT_ID
     *
     * @mbggenerated
     */
    public String getHabitId() {
        return habitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.HABIT_ID
     *
     * @param habitId the value for grow_up_user_hibit.HABIT_ID
     *
     * @mbggenerated
     */
    public void setHabitId(String habitId) {
        this.habitId = habitId == null ? null : habitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.CREATE_TIME
     *
     * @return the value of grow_up_user_hibit.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.CREATE_TIME
     *
     * @param createTime the value for grow_up_user_hibit.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.DELETE_TIME
     *
     * @return the value of grow_up_user_hibit.DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.DELETE_TIME
     *
     * @param deleteTime the value for grow_up_user_hibit.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_hibit.DELETE_FLG
     *
     * @return the value of grow_up_user_hibit.DELETE_FLG
     *
     * @mbggenerated
     */
    public Byte getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_hibit.DELETE_FLG
     *
     * @param deleteFlg the value for grow_up_user_hibit.DELETE_FLG
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Byte deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}