package pri.growup.persistence.dto;

import java.util.Date;
import pri.growup.persistence.BaseDto;

public class GrowUpVlogMain extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.VLOG_MAIN_ID
     *
     * @mbggenerated
     */
    private String vlogMainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.VLOG_TEXT
     *
     * @mbggenerated
     */
    private String vlogText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.VLOG_ID
     *
     * @mbggenerated
     */
    private String vlogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.DELETE_TIME
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_vlog_main.DELETE_FLG
     *
     * @mbggenerated
     */
    private Byte deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.VLOG_MAIN_ID
     *
     * @return the value of grow_up_vlog_main.VLOG_MAIN_ID
     *
     * @mbggenerated
     */
    public String getVlogMainId() {
        return vlogMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.VLOG_MAIN_ID
     *
     * @param vlogMainId the value for grow_up_vlog_main.VLOG_MAIN_ID
     *
     * @mbggenerated
     */
    public void setVlogMainId(String vlogMainId) {
        this.vlogMainId = vlogMainId == null ? null : vlogMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.USER_ID
     *
     * @return the value of grow_up_vlog_main.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.USER_ID
     *
     * @param userId the value for grow_up_vlog_main.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.VLOG_TEXT
     *
     * @return the value of grow_up_vlog_main.VLOG_TEXT
     *
     * @mbggenerated
     */
    public String getVlogText() {
        return vlogText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.VLOG_TEXT
     *
     * @param vlogText the value for grow_up_vlog_main.VLOG_TEXT
     *
     * @mbggenerated
     */
    public void setVlogText(String vlogText) {
        this.vlogText = vlogText == null ? null : vlogText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.VLOG_ID
     *
     * @return the value of grow_up_vlog_main.VLOG_ID
     *
     * @mbggenerated
     */
    public String getVlogId() {
        return vlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.VLOG_ID
     *
     * @param vlogId the value for grow_up_vlog_main.VLOG_ID
     *
     * @mbggenerated
     */
    public void setVlogId(String vlogId) {
        this.vlogId = vlogId == null ? null : vlogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.CREATE_TIME
     *
     * @return the value of grow_up_vlog_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.CREATE_TIME
     *
     * @param createTime the value for grow_up_vlog_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.DELETE_TIME
     *
     * @return the value of grow_up_vlog_main.DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.DELETE_TIME
     *
     * @param deleteTime the value for grow_up_vlog_main.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_vlog_main.DELETE_FLG
     *
     * @return the value of grow_up_vlog_main.DELETE_FLG
     *
     * @mbggenerated
     */
    public Byte getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_vlog_main.DELETE_FLG
     *
     * @param deleteFlg the value for grow_up_vlog_main.DELETE_FLG
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Byte deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}