package pri.growup.persistence.dto;

import java.util.Date;
import pri.growup.base.persistence.BaseDto;

public class GrowUpUserSigninRecord extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.SIGN_IN_RECORD_ID
     *
     * @mbggenerated
     */
    private String signInRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.SIGN_IN_TIME
     *
     * @mbggenerated
     */
    private Date signInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.SIGN_OUT_TIME
     *
     * @mbggenerated
     */
    private Date signOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.DELETE_TIME
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_user_signin_record.DELETE_FLG
     *
     * @mbggenerated
     */
    private Byte deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.SIGN_IN_RECORD_ID
     *
     * @return the value of grow_up_user_signin_record.SIGN_IN_RECORD_ID
     *
     * @mbggenerated
     */
    public String getSignInRecordId() {
        return signInRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.SIGN_IN_RECORD_ID
     *
     * @param signInRecordId the value for grow_up_user_signin_record.SIGN_IN_RECORD_ID
     *
     * @mbggenerated
     */
    public void setSignInRecordId(String signInRecordId) {
        this.signInRecordId = signInRecordId == null ? null : signInRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.USER_ID
     *
     * @return the value of grow_up_user_signin_record.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.USER_ID
     *
     * @param userId the value for grow_up_user_signin_record.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.SIGN_IN_TIME
     *
     * @return the value of grow_up_user_signin_record.SIGN_IN_TIME
     *
     * @mbggenerated
     */
    public Date getSignInTime() {
        return signInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.SIGN_IN_TIME
     *
     * @param signInTime the value for grow_up_user_signin_record.SIGN_IN_TIME
     *
     * @mbggenerated
     */
    public void setSignInTime(Date signInTime) {
        this.signInTime = signInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.SIGN_OUT_TIME
     *
     * @return the value of grow_up_user_signin_record.SIGN_OUT_TIME
     *
     * @mbggenerated
     */
    public Date getSignOutTime() {
        return signOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.SIGN_OUT_TIME
     *
     * @param signOutTime the value for grow_up_user_signin_record.SIGN_OUT_TIME
     *
     * @mbggenerated
     */
    public void setSignOutTime(Date signOutTime) {
        this.signOutTime = signOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.CREATE_TIME
     *
     * @return the value of grow_up_user_signin_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.CREATE_TIME
     *
     * @param createTime the value for grow_up_user_signin_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.DELETE_TIME
     *
     * @return the value of grow_up_user_signin_record.DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.DELETE_TIME
     *
     * @param deleteTime the value for grow_up_user_signin_record.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_user_signin_record.DELETE_FLG
     *
     * @return the value of grow_up_user_signin_record.DELETE_FLG
     *
     * @mbggenerated
     */
    public Byte getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_user_signin_record.DELETE_FLG
     *
     * @param deleteFlg the value for grow_up_user_signin_record.DELETE_FLG
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Byte deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}