package pri.growup.persistence.dto;

import java.util.Date;
import pri.growup.persistence.BaseDto;

public class GrowUpHabit extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_habit.HABIT_ID
     *
     * @mbggenerated
     */
    private String habitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_habit.HABIT_NAME
     *
     * @mbggenerated
     */
    private String habitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_habit.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_habit.DELETE_TIME
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_habit.DELETE_FLG
     *
     * @mbggenerated
     */
    private Byte deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_habit.HABIT_ID
     *
     * @return the value of grow_up_habit.HABIT_ID
     *
     * @mbggenerated
     */
    public String getHabitId() {
        return habitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_habit.HABIT_ID
     *
     * @param habitId the value for grow_up_habit.HABIT_ID
     *
     * @mbggenerated
     */
    public void setHabitId(String habitId) {
        this.habitId = habitId == null ? null : habitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_habit.HABIT_NAME
     *
     * @return the value of grow_up_habit.HABIT_NAME
     *
     * @mbggenerated
     */
    public String getHabitName() {
        return habitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_habit.HABIT_NAME
     *
     * @param habitName the value for grow_up_habit.HABIT_NAME
     *
     * @mbggenerated
     */
    public void setHabitName(String habitName) {
        this.habitName = habitName == null ? null : habitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_habit.CREATE_TIME
     *
     * @return the value of grow_up_habit.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_habit.CREATE_TIME
     *
     * @param createTime the value for grow_up_habit.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_habit.DELETE_TIME
     *
     * @return the value of grow_up_habit.DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_habit.DELETE_TIME
     *
     * @param deleteTime the value for grow_up_habit.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_habit.DELETE_FLG
     *
     * @return the value of grow_up_habit.DELETE_FLG
     *
     * @mbggenerated
     */
    public Byte getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_habit.DELETE_FLG
     *
     * @param deleteFlg the value for grow_up_habit.DELETE_FLG
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Byte deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}