package pri.growup.persistence.dto;

import pri.growup.base.persistence.BaseDto;

public class GrowUpCommonId extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grow_up_common_id.COMMON_ID
     *
     * @mbggenerated
     */
    private Integer commonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grow_up_common_id.COMMON_ID
     *
     * @return the value of grow_up_common_id.COMMON_ID
     *
     * @mbggenerated
     */
    public Integer getCommonId() {
        return commonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grow_up_common_id.COMMON_ID
     *
     * @param commonId the value for grow_up_common_id.COMMON_ID
     *
     * @mbggenerated
     */
    public void setCommonId(Integer commonId) {
        this.commonId = commonId;
    }
}