CREATE DATABASE IF NOT EXISTS grow_up;
USE grow_up;
CREATE TABLE IF NOT EXISTS GROW_UP_SIGNIN_USER (
  USER_ID     VARCHAR(20) PRIMARY KEY
  COMMENT '用户id',
  USER_NAME   VARCHAR(10) NOT NULL
  COMMENT '登录用户名称',
  USER_PWD    VARCHAR(50) NOT NULL
  COMMENT '登录用户密码',
  USER_PHONE  VARCHAR(11) NOT NULL
  COMMENT '用户电话',
  IDENTITY_ID TINYINT   DEFAULT 0
  COMMENT '身份所屬id',
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG  TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '用户信息表';

CREATE TABLE IF NOT EXISTS GROW_UP_USER_IDENTITY (
  IDENTITY_ID   TINYINT PRIMARY KEY
  COMMENT '身份所屬id',
  IDENTITY_NAME VARCHAR(10) NOT NULL
  COMMENT '身份名称',
  CREATE_TIME   TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME   TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG    TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '身份类别表';

CREATE TABLE IF NOT EXISTS GROW_UP_USER_SIGNIN_RECORD (
  SIGN_IN_RECORD_ID VARCHAR(20) PRIMARY KEY
  COMMENT '登录记录id',
  USER_ID         VARCHAR(20) NOT NULL
  COMMENT '用户id',
  SIGN_IN_TIME     TIMESTAMP DEFAULT current_timestamp
  COMMENT '登录时间',
  SIGN_OUT_TIME    TIMESTAMP
  COMMENT '登出时间',
  CREATE_TIME     TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME     TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG      TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '用户登录记录表';

CREATE TABLE IF NOT EXISTS GROW_UP_VLOG_MAIN (
  VLOG_MAIN_ID VARCHAR(20) PRIMARY KEY
  COMMENT 'vlog主表id',
  USER_ID     VARCHAR(20) NOT NULL
  COMMENT '用户id',
  VLOG_TEXT   VARCHAR(500)
  COMMENT 'vlog附带文字信息',
  VLOG_ID     VARCHAR(20) NOT NULL
  COMMENT 'vlogId',
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG  TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT 'vlog信息主表';

CREATE TABLE IF NOT EXISTS GROW_UP_VLOG (
  VLOG_ID     VARCHAR(20) PRIMARY KEY
  COMMENT 'vlogid',
  VLOG_PATH   VARCHAR(100) NOT NULL
  COMMENT 'vlog存储路径（包含文件名）',
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG  TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT 'vlog辅助信息表';

CREATE TABLE IF NOT EXISTS GROW_UP_HABIT (
  HABIT_ID    VARCHAR(20) PRIMARY KEY
  COMMENT '习惯id',
  HABIT_NAME  VARCHAR(20) NOT NULL
  COMMENT '习惯名称',
  CREATE_TIME TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG  TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '习惯表';

CREATE TABLE IF NOT EXISTS GROW_UP_USER_HIBIT (
  USER_HABIT_ID VARCHAR(20) PRIMARY KEY
  COMMENT '用户习惯表id',
  USER_ID      VARCHAR(20) NOT NULL
  COMMENT '用户id',
  HABIT_ID     VARCHAR(20) NOT NULL
  COMMENT '习惯id',
  CREATE_TIME  TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME  TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG   TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '用户习惯表';

CREATE TABLE IF NOT EXISTS GROW_UP_HABIT_RECORD (
  HABIT_RECORD_ID VARCHAR(20) PRIMARY KEY
  COMMENT '习惯完成记录id',
  USER_ID        VARCHAR(20) NOT NULL
  COMMENT '用户id',
  HABIT_ID       VARCHAR(20) NOT NULL
  COMMENT '习惯id',
  CREATE_TIME    TIMESTAMP DEFAULT current_timestamp
  COMMENT '创建时间',
  DELETE_TIME    TIMESTAMP
  COMMENT '删除时间',
  DELETE_FLG     TINYINT   DEFAULT 0
  COMMENT '删除标记'
)
  COMMENT '习惯完成记录表';

